version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 061803398
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:061803398@db:5432/postgres
    volumes:
      - .:/app
    command: ["./wait-for-db.sh", "db", "python", "carregamento.py"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
